<?xml version="1.0" encoding="UTF-8"?>

<ClassDiagram name="eva3_7_throw_exception">
  <ClassDiagramComponents>
    <Class name="EVA3_7_THROW_EXCEPTION" package="eva3_7_throw_exception" visibility="public" xPosition="20.0" yPosition="20.0">
      <Fields/>
      <Constructors/>
      <Methods>
        <Method name="main" returnType="void" visibility="public" isStatic="true">
          <Argument type="String[]" name="args"/>
        </Method>
      </Methods>
    </Class>
    <Class name="Prueba" package="eva3_7_throw_exception" visibility="public" xPosition="320.0" yPosition="20.0">
      <Fields/>
      <Constructors/>
      <Methods>
        <Method name="CapturaMCero" returnType="void" visibility="public">
          <Argument type="int" name="valor"/>
        </Method>
        <Method name="division" returnType="int" visibility="public">
          <Argument type="int" name="x"/>
          <Argument type="int" name="y"/>
        </Method>
      </Methods>
    </Class>
  </ClassDiagramComponents>
  <ClassDiagramRelations/>
</ClassDiagram>
